# # Generated by Selenium IDE
# import pytest
# import time
# from selenium import webdriver
# from webdriver_manager.chrome import ChromeDriverManager
# from selenium.webdriver.chrome.service import Service
# from selenium.webdriver.common.by import By

# class TestAddbook():
#     def setup_method(self, method):
#         options = webdriver.ChromeOptions()
#         # options.add_argument('--headless')  # Décommente si tu veux sans UI
#         options.add_argument('--window-size=810,1063')
#         self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)

#     def teardown_method(self, method):
#         self.driver.quit()

#     def test_addbook(self):
#         self.driver.get("http://localhost:5173/")
#         self.driver.find_element(By.CSS_SELECTOR, ".btn-success").click()
#         self.driver.find_element(By.ID, "addBookTitle").click()
#         self.driver.find_element(By.ID, "addBookTitle").send_keys("Test")
#         self.driver.find_element(By.ID, "addBookAuthor").click()
#         self.driver.find_element(By.ID, "addBookAuthor").send_keys("Tom")
#         self.driver.find_element(By.CSS_SELECTOR, ".modal:nth-child(2) .btn:nth-child(1)").click()

#         time.sleep(1)

#         # Vérifie si le livre a été ajouté
#         alert = self.driver.find_element(By.CSS_SELECTOR, ".alert-success")
#         assert "Book added!" in alert.text
