name: CI - Flask CRUD (unit tests only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests with pytest
      run: |
        cd server
        pytest --html=pytest-report.html


    - name: Upload pytest report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: server/pytest-report.html
